### ISSUE TITLE
1- initial installation Symphony 5.4.12 =>halt aday.... now updated to 6.1.4

### ISSUE THREAD

**Issue by tanguyguillo** [tanguyguillo/snowtricks#1]
testing with symfony 6.14 and php 8.1.8 but with my Imac from 2014, a lot of things to fix,so i re install V5 @castroCrea

<img width="1154" alt="Capture d’écran 2022-09-13 à 16 51 58" src="https://user-images.githubusercontent.com/18627668/189934198-9bf47983-9dcc-4dce-b08b-8d4641a538a6.png">

but online version6 working....

<img width="1156" alt="Capture d’écran 2022-09-13 à 16 53 23" src="https://user-images.githubusercontent.com/18627668/189934463-4832ac96-facd-4bc4-8026-1923abca66f3.png">

So I don't know exactly what to do, i'll preffert to work with V6 but......

**Comment by tanguyguillo** [comment]
In fact i was upset to can't install the last version of symfony on my Imac so :

what i did : 

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh) »

brew list
brew install wget
brew install php                        did it  (/usr/local/etc/php/8.1)
brew install mysql                     did it
brew services start mysql         did it
brew services start php            did it
brew services restart php   not did it for now
brew install composer  did it

valet                                           not did il 

so after update symfony 

php composer.phar update "symfony/*" --with-all-dependencies

and now in mamp in local aera


<img width="1221" alt="Capture d’écran 2022-09-15 à 12 02 40" src="https://user-images.githubusercontent.com/18627668/190377493-5357de79-e6ea-4a3c-bbd4-5f79b103c081.png">

and on line https://snowtricks.omegawebprod.com/

<img width="1220" alt="Capture d’écran 2022-09-15 à 12 11 02" src="https://user-images.githubusercontent.com/18627668/190377894-d82e73bc-75bf-4b1f-8ba7-0d0a1ece03ae.png">

not the same color (update  from V5 ?)  but same version between local and online.... i'am happy....  @castroCrea

**Comment by tanguyguillo** [comment]
but since the files names did nt change git don't see the modification.... bad....

**Comment by tanguyguillo** [comment]
bundle officiallist 👍 

https://symfony.com/bundles

**Comment by castroCrea** [comment]
Woop woop





Paolo Castro
Lazy CTO
***@***.***

**Comment by tanguyguillo** [comment]
Deleting the space snowtricks-omega  /nowtricks
<img width="1773" alt="Capture d’écran 2022-09-15 à 11 54 14" src="https://user-images.githubusercontent.com/18627668/190491272-ec474d70-09cf-4dfd-9c77-701067442beb.png">
and the color change to purple to green :


<img width="1136" alt="Capture d’écran 2022-09-15 à 21 23 36" src="https://user-images.githubusercontent.com/18627668/190491676-af258266-2de8-437c-9787-bfcad2b45f7a.png">

**Comment by tanguyguillo** [comment]
in fact when i did git add . etc .... almost none files were to push on main branch.... it's seems to me anormal....

**Comment by tanguyguillo** [comment]
and now pour CLI:

brew install symfony-cli/tap/symfony-cli
brew link --overwrite symfony-cli
