### ISSUE TITLE
 not blocking but issue during migration

### ISSUE THREAD

**Issue by tanguyguillo** [tanguyguillo/snowtricks#24]
When i did

php bin/console make:migration
php bin/console doctrine:migrations:migrate

to correct picure field in picture.... every thing is ok but i had this message : (did 'en block something)

<img width="463" alt="Capture d’écran 2023-01-19 à 13 38 01" src="https://user-images.githubusercontent.com/18627668/213446054-09cbd906-7790-4717-8c6a-bce68ace41da.png">

@castroCrea   what do you thing of ift?

**Comment by castroCrea** [comment]
this means that in DB you have on migration that is there but there is no file matching on you migration folder

**Comment by tanguyguillo** [comment]
For now OK .... test a total: php bin/console make:migration
php bin/console doctrine:migrations:migrate.... next time
