### ISSUE TITLE
Create auth system 

### ISSUE THREAD

**Issue by castroCrea** [tanguyguillo/snowtricks#5]

**Comment by castroCrea** [comment]
https://symfony.com/doc/current/security.html

**Comment by tanguyguillo** [comment]
made auth : here test5@test5.fr

<img width="1482" alt="Capture d’écran 2022-10-20 à 06 18 34" src="https://user-images.githubusercontent.com/18627668/196855435-83702935-dab0-40ef-8ac9-ab4ef2d68fd7.png">

<img width="1500" alt="Capture d’écran 2022-10-20 à 06 14 47" src="https://user-images.githubusercontent.com/18627668/196855024-7205aa5e-5e62-436f-b1aa-07f22bf2c0bc.png">

with in DB token  check token and date. @castroCrea 

<img width="1616" alt="Capture d’écran 2022-10-20 à 06 16 02" src="https://user-images.githubusercontent.com/18627668/196855207-0a132ea0-81a0-4fc8-97ea-0cb95d504f7a.png">
