### ISSUE TITLE
CRUD tricks

### ISSUE THREAD

**Issue by castroCrea** [tanguyguillo/snowtricks#6]

**Comment by tanguyguillo** [comment]
create OK
<img width="909" alt="Capture d’écran 2022-12-28 à 12 57 07" src="https://user-images.githubusercontent.com/18627668/209930717-12738edb-545f-47e3-b5e9-e68658eb74f3.png">

<img width="1140" alt="Capture d’écran 2022-12-28 à 13 08 08" src="https://user-images.githubusercontent.com/18627668/209930728-e21d076d-89ff-47dd-a69a-62b8a4de4013.png">

**Comment by tanguyguillo** [comment]
for the delete on main page it's ok also OK
<img width="1799" alt="Capture d’écran 2023-01-18 à 14 16 58" src="https://user-images.githubusercontent.com/18627668/213181680-40c04d69-3665-4265-8e48-78057e928e0a.png">

for the delate on update page, also OK (still an issue for the update)

<img width="715" alt="Capture d’écran 2023-01-18 à 14 23 13" src="https://user-images.githubusercontent.com/18627668/213182867-7d82413a-347b-43f2-aff3-dc0b86788bbc.png">
